name: geopoint
description: Geospatial data structures. Provides GeoPoint and GeoSerie models.
homepage: https://github.com/synw/geopoint
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  latlong2: ^0.8.0
  slugify: ^2.0.0

dev_dependencies:
  extra_pedantic: ^1.4.0
  test: ^1.17.4
